### PR TITLE
Updating Node Packages

### PR DESCRIPTION
**Pull request by mohabghanem**
Updating 'debug' package due to security vulnerability.

### CODE REVIEW

**Comment by mohabghanem** [comment]
@v-geberr Please review if you are the one maintaining this repository

**Comment by mohabghanem** [comment]
@yshahin @wiazur

**Comment by mohabghanem** [comment]
Hi @peterblazejewicz , this package was already there in the sample code. I just updated it because there was a security vulnerability in the older version.

**Comment by peterblazejewicz** [comment]
This is addition, not update:
https://github.com/Microsoft/LUIS-Samples/pull/190/files#diff-28eb2229f81e6ced69cc77f3a7f3e921R14
Don't want to crash copies on this, but the update is simply not required.
Thanks!

**Comment by mohabghanem** [comment]
The main reason behind this pull request is that we received a security vulnerability warning in the debug package, which was originally in package-lock before, I just updated it.  But if the package was not in package.json in the first place, how could it be in package-lock.json?

**Comment by mohabghanem** [comment]
@diberry  I followed the steps you mentioned, and updated the pull request, but the Debug package still shows in package-lock.

**Comment by diberry** [comment]
@mohabghanem Thank you for your patience with this PR. I went through all the Node.js examples and installed. The quickest fix was to remove the package-lock.json from this particular one. This allows the npm install to update the packages as part of the install instead of dealing with audit failures from the package-lock.json. If you find an issue still exists in this, or another sample, please let me know.

**Pull request closed without merging**
